Main svc
NastasyaRosh/java-explore-with-me pull request #4
Opened 2023-06-22 19:36 UTC by NastasyaRosh

2023-06-24 06:58 UTC, sergeymamonov requested changes

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/event/property/EventSort.java
> +    EventSort(String value) {
А если аннотациями сделать конструктор и геттер?

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/event/service/EventService.java
> +    List<Event> findByParams(
Не требую изменений, для информации. Если в метод нужно передать много параметров, то лучше сделать объект, в который положить все эти параметры. И тогда в метод нужно будет передать только один этот объект. Плюс если добавится еще один параметр, который нужно будет передать в метод, то нужно будет добавить поле в класс. Сигнатура метода при этом не изменится.

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +            setTransientFields(event);
Здесь выполняются запросы к БД в цикле.

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/event/stat/EventStatService.java
> +                throw new RuntimeException(e);
Лучше не кидать RuntimeException. А создать свое собственное исключение. RuntimeException может возникнуть во многих местах, а по своему исключению легче понять откуда исключение.

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/exception/ErrorHandler.java
> +}
Лучше еще добавить обработку Runtime ошибок.

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/request/repository/RequestRepository.java
> +    Map<Long, Integer> findCountRequestsByEventIdsAndStatus(List<Long> eventIds, RequestStatus status);
Используется ли где-то этот метод?

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/request/service/RequestServiceImpl.java
> +                && status.equals(RequestStatus.CONFIRMED)
Лучше поменять RequestStatus.CONFIRMED.equals(). Ниже аналогично.

2023-06-24 06:58 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/utility/Utility.java
> +        if (newVal == null) {
Раз в нескольких ветках возвращаем val, то условия можно объединить.

2023-06-25 00:32 UTC, NastasyaRosh commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +            setTransientFields(event);
Насколько я поняла нельзя Map записывать из БД прямо, поэтому пришлось создать новый класс

2023-06-25 00:32 UTC, NastasyaRosh commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/event/service/EventService.java
> +    List<Event> findByParams(
Спасибо :)

2023-06-25 11:34 UTC, sergeymamonov approved these changes

2023-06-25 11:34 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewmservice/request/service/RequestServiceImpl.java
> +        if (!event.getState().equals(EventState.PUBLISHED)) {
Поменять местами.

2023-06-25 18:31 UTC, merged